version: '3'

networks:
  homework-network:
    driver: bridge

services:
  clusterf-proxy:
    image: andymacdonald/clusterf-chaos-proxy
    container_name: clusterf-proxy
    environment:
      JAVA_OPTS: "-Dchaos.strategy=RANDOM_HAVOC -Ddestination.hostProtocolAndPort=http://database:3100 -Dchaos.strategy.delayResponse.random.maxSeconds=10"
    ports:
      - "8088:8080"
    depends_on:
      - database
    networks:
      - homework-network

  database:
    container_name: database
    image: mitchallen/random-server
    expose:
    - 3100
    networks:
      - homework-network

  homework:
    build: .
    container_name: homework
    ports:
      - "8080:8080"
    networks:
      - homework-network
    depends_on:
      - clusterf-proxy
